{
  "PageType": 0,
  "ColumnCount": 56,
  "RowCount": 61,
  "Formulas": {
    "2,20": "ODATA(\"VW_MAY_REPORT_ALTRAA?$select=STYLE_LIST&$filter=DEPARTMENTID eq \"&IF(ISBLANK(B3),\"null\",\"'\"&B3&\"'\")&\" and DATETIME eq \"&IF(ISBLANK(AT3),\"null\",TEXT(AT3,\"yyyy-MM-ddThh:mm:ssZ\"))&\"&$top=1\")",
    "54,44": "IFERROR(ODATA(\"DAILY_OUTPUT?$select=TIME5&$filter=WC_NO eq \"&IF(ISBLANK(B3),\"null\",B3)&\" and DATE_TIME eq \"&IF(ISBLANK(AT3),\"null\",TEXT(AT3,\"yyyy-MM-ddThh:mm:ssZ\"))),\"\")",
    "51,44": "SUM(AS6)",
    "54,47": "IFERROR(ODATA(\"DAILY_OUTPUT?$select=TIME6&$filter=WC_NO eq \"&IF(ISBLANK(B3),\"null\",B3)&\" and DATE_TIME eq \"&IF(ISBLANK(AT3),\"null\",TEXT(AT3,\"yyyy-MM-ddThh:mm:ssZ\"))),\"\")",
    "54,32": "IFERROR(ODATA(\"DAILY_OUTPUT?$select=TIME3&$filter=WC_NO eq \"&IF(ISBLANK(B3),\"null\",B3)&\" and DATE_TIME eq \"&IF(ISBLANK(AT3),\"null\",TEXT(AT3,\"yyyy-MM-ddThh:mm:ssZ\")))/2,\"\")",
    "57,50": "IFERROR(AY52/AY55,0)",
    "57,47": "IFERROR(AV52/AV55,0)",
    "57,44": "IFERROR(AS52/AS55,0)",
    "51,26": "SUM(AA6)",
    "51,38": "SUM(AM6)",
    "57,35": "IFERROR(AJ52/AJ55,0)",
    "51,41": "SUM(AP6)",
    "54,35": "IFERROR(ODATA(\"DAILY_OUTPUT?$select=TIME3&$filter=WC_NO eq \"&IF(ISBLANK(B3),\"null\",B3)&\" and DATE_TIME eq \"&IF(ISBLANK(AT3),\"null\",TEXT(AT3,\"yyyy-MM-ddThh:mm:ssZ\")))/2,\"\")",
    "54,29": "IFERROR(ODATA(\"DAILY_OUTPUT?$select=TIME2&$filter=WC_NO eq \"&IF(ISBLANK(B3),\"null\",B3)&\" and DATE_TIME eq \"&IF(ISBLANK(AT3),\"null\",TEXT(AT3,\"yyyy-MM-ddThh:mm:ssZ\")))/2,\"\")",
    "54,20": "IFERROR(ODATA(\"DAILY_OUTPUT?$select=TIME1&$filter=WC_NO eq \"&IF(ISBLANK(B3),\"null\",B3)&\" and DATE_TIME eq \"&IF(ISBLANK(AT3),\"null\",TEXT(AT3,\"yyyy-MM-ddThh:mm:ssZ\")))/2,\"\")",
    "54,23": "IFERROR(ODATA(\"DAILY_OUTPUT?$select=TIME1&$filter=WC_NO eq \"&IF(ISBLANK(B3),\"null\",B3)&\" and DATE_TIME eq \"&IF(ISBLANK(AT3),\"null\",TEXT(AT3,\"yyyy-MM-ddThh:mm:ssZ\")))/2,\"\")",
    "51,32": "SUM(AG6)",
    "54,38": "IFERROR(ODATA(\"DAILY_OUTPUT?$select=TIME4&$filter=WC_NO eq \"&IF(ISBLANK(B3),\"null\",B3)&\" and DATE_TIME eq \"&IF(ISBLANK(AT3),\"null\",TEXT(AT3,\"yyyy-MM-ddThh:mm:ssZ\")))/2,\"\")",
    "54,41": "IFERROR(ODATA(\"DAILY_OUTPUT?$select=TIME4&$filter=WC_NO eq \"&IF(ISBLANK(B3),\"null\",B3)&\" and DATE_TIME eq \"&IF(ISBLANK(AT3),\"null\",TEXT(AT3,\"yyyy-MM-ddThh:mm:ssZ\")))/2,\"\")",
    "51,23": "SUM(X6)",
    "51,20": "SUM(U6)",
    "57,41": "IFERROR(AP52/AP55,0)",
    "51,50": "SUM(AY6)",
    "57,32": "IFERROR(AG52/AG55,0)",
    "51,35": "SUM(AJ6)",
    "57,26": "IFERROR(AA52/AA55,0)",
    "54,26": "IFERROR(ODATA(\"DAILY_OUTPUT?$select=TIME2&$filter=WC_NO eq \"&IF(ISBLANK(B3),\"null\",B3)&\" and DATE_TIME eq \"&IF(ISBLANK(AT3),\"null\",TEXT(AT3,\"yyyy-MM-ddThh:mm:ssZ\")))/2,\"\")",
    "57,29": "IFERROR(AD52/AD55,0)",
    "57,23": "IFERROR(X52/X55,0)",
    "51,47": "SUM(AV6)",
    "51,29": "SUM(AD6)",
    "57,38": "IFERROR(AM52/AM55,0)",
    "54,50": "SUM(U55:AX57)",
    "57,20": "IFERROR(U52/U55,0)"
  }
}